version: "3.2"
services:
  monitor:
    image: thunder_bridge/monitor
    build: .
    ports:
     - "4000:3000"
    env_file: .env
    environment:
     - REDIS_URL=redis://redis
     - SENTRY_DSN=
    command: npm run start
    depends_on:
      - redis
  redis:
    image: "redis:4"
    ports:
     - "6379:6379"
